// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-PS0_bN5n1KtVvqjKnpp7Hu-_OzIkBLQ',
    appId: '1:1044190692077:web:a84801bba1431ef754c2e4',
    messagingSenderId: '1044190692077',
    projectId: 'aurum-fashion-store',
    authDomain: 'aurum-fashion-store.firebaseapp.com',
    storageBucket: 'aurum-fashion-store.firebasestorage.app',
    measurementId: 'G-JJ4DRL3BKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXu6u3qljQ96MJU_MZEksrR5O6pS6YJqA',
    appId: '1:1044190692077:android:61fa9a8002a919ce54c2e4',
    messagingSenderId: '1044190692077',
    projectId: 'aurum-fashion-store',
    storageBucket: 'aurum-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn6NABDTyczCpdGwEvWrp2LZvEf-HmVt8',
    appId: '1:1044190692077:ios:385ace66620b4f4654c2e4',
    messagingSenderId: '1044190692077',
    projectId: 'aurum-fashion-store',
    storageBucket: 'aurum-fashion-store.firebasestorage.app',
    iosBundleId: 'com.example.flutterAurumLuxuryFashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn6NABDTyczCpdGwEvWrp2LZvEf-HmVt8',
    appId: '1:1044190692077:ios:385ace66620b4f4654c2e4',
    messagingSenderId: '1044190692077',
    projectId: 'aurum-fashion-store',
    storageBucket: 'aurum-fashion-store.firebasestorage.app',
    iosBundleId: 'com.example.flutterAurumLuxuryFashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-PS0_bN5n1KtVvqjKnpp7Hu-_OzIkBLQ',
    appId: '1:1044190692077:web:6c0e9f6ed9c7c6ba54c2e4',
    messagingSenderId: '1044190692077',
    projectId: 'aurum-fashion-store',
    authDomain: 'aurum-fashion-store.firebaseapp.com',
    storageBucket: 'aurum-fashion-store.firebasestorage.app',
    measurementId: 'G-XST253SF8E',
  );
}
